login:
    pattern:   /login
    defaults:  { _controller: TyrBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

projects:
    type: rest
    resource: Ymir\YmirTyrBundle\Controller\ProjectController

pages:
    type: rest
    resource: Ymir\YmirTyrBundle\Controller\PageController
