tyr:
    resource: "@TyrBundle/Controller/"
    type:     annotation

ymir_tyr:
    resource: "@TyrBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

