<?php

namespace Ymir\YmirTyrBundle\Entity;

/**
 * MetaWidgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetaWidgetRepository extends \Doctrine\ORM\EntityRepository
{
}
